### ISSUE TITLE
Incorrect date in backstagepro data

### ISSUE THREAD

**Issue by ropfoo** [ropfoo/tonemato#10]
The api returns '01.01.2023' instead of the actual date of the post. This does not apply to every post though so it could either be a scraping or date parsing issue. Did not test it for other domains yet.

**Comment by robinduerhager** [comment]
After updating the cache, the problem resolved itself. A route or parameter on `NODE_ENV==='development'` which manually updates the cache would be nice. Transferring to new Issue.

**Comment by ropfoo** [comment]
Unfortunately that is not the actual reason. Did some research and it turns out that sometimes the currently scraped date element does not include the date but a string saying '[in Grundung]' which then gets converted to a default date which is '01.01.2023'

<img width="490" alt="Screenshot 2023-04-16 at 19 17 57" src="https://user-images.githubusercontent.com/18482002/232329519-ceed91d7-bd1f-470b-8ad1-baf4a8a070e0.png">

**Comment by ropfoo** [comment]
Gonna fix this real quick

**Comment by robinduerhager** [comment]
But why did it fetch the correct date after manually triggering a cache update then? 😅

**Comment by ropfoo** [comment]
Well that would be really strange do you have a screenshot? Because the cache does not mutate any of the scraped data right now so it must be a scraping issue. Maybe the cache update just returned new posts that coincendentially had a propper date value?

**Comment by robinduerhager** [comment]
Don't have a screenshot right now, but i noticed that drilbur returned valid data, while ralts sometimes returned 01.01.2023. I then updated the cache and the false data was removed.

**Comment by ropfoo** [comment]
I suggest checking the drilbur response again in the current develop branch and im sure you will find some '01.01.2023's in there. Tested it myself and it was in fact a scraping issue based on the wrong element target. 
As I said this is not a general issue. It only occurs when the corresponding div in backstagepro has an element before the date span. So this is definitly the reason for this bug to happen. (see #19 )

Why would the cache return a wrong date format otherwise? It should not matter how often you update the cache. Updating the cache more often only returns fresh data but there should never be a scenario where stale data suddenly is all wrong.

**Comment by robinduerhager** [comment]
Yeah i tested it again and it indeed is a scraping issue. Maybe i updated the code myself before and my build process didn't update or so.
