### ISSUE TITLE
Create fancy filter - desktop

### ISSUE THREAD

**Issue by ropfoo** [ropfoo/tonemato#13]
Create an air bnb like filter component to submit personalized requests to the teasers endpoint.

**Comment by robinduerhager** [comment]
What are the categories of the filter? I think we already had these right?

* Searching for Band / Band Searching Musician
* Instrument
* City

Also thought about things like

* Genre (so you don't get Popmusic bandresults in case you want to play in a metal band)
* Perimeter (like if you want to search bands that are only 20km away or so)

**Comment by ropfoo** [comment]
Since this component is starting to become fairly complex and the ux is gonna change drastically on mobile I'm gonna separate this issue into two main parts (desktop and mobile).
