### ISSUE TITLE
Prettify api response

### ISSUE THREAD

**Issue by ropfoo** [ropfoo/tonemato#17]
Right now the response from ralts just 'copies' the returned scrape from drilbur.
For the frontend there should be a much more simplified version of that..
Maybe we can keep the pages for now (eg. for lazy loading later on) but we should definitely merge all domain results.

So instead of: 
```ts
{
  ...
  cache: {
    domainName: {
      pages: [[{ ...domainTeaser }], [{ ...domainTeaser }]],
    },
  },
}
```

Something more flat like:
```ts
{
 ...
 data: [[{ ...teaser }], [{ ...teaser }]],
}
```

**Comment by robinduerhager** [comment]
Ralts now delivers:

```js
{
  cache: [ { ...teaser }, { ...teaser }, ... ]
}
```

![ralts_output](https://user-images.githubusercontent.com/18482238/232935295-641adb04-6373-4652-a5de-de66650c1737.png)

Can create PR after #28 is fixed.

**Comment by ropfoo** [comment]
Looks nice, but I would not call the attribute "cache" since there isn't really an alternative for the Frontend to fetch from - I would go with something like "teasers" instead.
Also there ist still the "type" attribute to point that out.

**Comment by robinduerhager** [comment]
Do we even need the `type: 'cache'` attribute? We can also just send an array to the frontend if we only have teasers in the cache.

**Comment by robinduerhager** [comment]
* `type: cache` should stay in ralts do be able to distinguish between a cached value and a freshly scraped value.
* `drilbur` should only deliver raw but structured scraped data to ralts and transform it just rudimentarily.
* The data from `drilbur` should be stored per site, so there should be a JSON which has a `musicstore` attribute with the musicstore scrape, a `backstagepro` attribute with the backstagepro scrape, etc.
