### ISSUE TITLE
Add Scripts to start single services

### ISSUE THREAD

**Issue by robinduerhager** [ropfoo/tonemato#24]
Being able to start single services locally could help in debugging them. Currently we always deploy the whole Infrastructure to Docker, though, often only a single service like `drilbur` implements a bug which diffuses through the whole software stack to the frontend. Deploy the whole infrastructure takes time so a `npm run dev:drilbur` etc. script would be helpful.

Deeply connected with #23

**Comment by ropfoo** [comment]
Well technically there already is a manual way to start single services (see the [README](https://github.com/RopFoo/tonemato#readme))

```bash
npx turbo run dev --filter=drilbur
```

**Comment by robinduerhager** [comment]
Yeah i just want to have a script that is basically an alias for that in the package.json so i can type `npm run dev:drilbur` :D

**Comment by robinduerhager** [comment]
`npm i -D esbuild` is somehow necessary for local windows builds, see https://github.com/evanw/esbuild/issues/1646#issuecomment-1069353130

**Comment by robinduerhager** [comment]
Closed by #27
