### ISSUE TITLE
Display some default value on missing image

### ISSUE THREAD

**Issue by robinduerhager** [ropfoo/tonemato#32]
Some teasers are missing an image which results in an empty image tag with a border. Maybe we should display some default image in that case based on the platform from which this teaser was fetched or remove the image completely?

![teaser](https://user-images.githubusercontent.com/18482238/233207015-a102c8d3-bf1b-4d2f-9ad0-9fba283a9482.png)

**Comment by ropfoo** [comment]
Yep that's definitely planned. We need those anyways since some platforms (musikersucht) dont even offer image uploads in the first place.  Would not remove it completely for layout reasons though.
