### ISSUE TITLE
🦥 "Chillbur" aka scrape less data in dev mode 

### ISSUE THREAD

**Issue by ropfoo** [ropfoo/tonemato#45]
Right now drilbur scrapes every page per domain per instrument per category which will result in long loading times when more instruments become a thing (#42).
This is fine and part of the scraping fun but in dev mode it would be nice to have a compromise between fresh data and short loading times when the docker containers initially start.
Maybe we could set a param chillbur=true which is always used in dev mode and tells drilbur to only scrape the first page per domain. Thoughts @robinduerhager ?

**Comment by robinduerhager** [comment]
In `.env`, the environemnt variable `NODE_ENV` can be set to `development` or `production`. We could also just make the scraping time shorter when development is set, like an automatic chillbur parameter. Or do you think we should be able to use the production scrape in development mode aswell and make a chillbur parameter available when `NODE_ENV=development` is set?

**Comment by ropfoo** [comment]
Thought of a new approach and developed a little service for mocking websites for scraping

[https://github.com/ropfoo/clobbopus](https://github.com/ropfoo/clobbopus)

already added it to the current go rewrite #48
