### ISSUE TITLE
Replace console logs with structured logging

### ISSUE THREAD

**Issue by robinduerhager** [ropfoo/tonemato#46]
[debug](https://www.npmjs.com/package/debug) is a handy little package which debug logs messages in categories. If we want to log messages in `smeargle`, we could set the environment variable `DEBUG` like so to switch `debug` active:

```.env
DEBUG=log,error
```

then in the code:

```js
const debug = require('debug');
const log = debug('log');
const error = debug('error');

// other code

log('hello there');
```

`debug` can be deactivated then with

```.env
#DEBUG=log,error
```
or you can just deactivate e.g. the error logs by uncommenting it like so

```.env
DEBUG=log #,error
```

**Comment by ropfoo** [comment]
as an alternative in the go world we could use ubers [zap](https://github.com/uber-go/zap) for structured logging
