### ISSUE TITLE
Rewrite drilbur in Go 

### ISSUE THREAD

**Issue by ropfoo** [ropfoo/tonemato#47]
Since go has a cooler mascot than ts (and go routines and better typing and better tooling and no js and better performance overall) it might be time to say goodbye (in the places we can)...

Listed some tools we could use in the process. 
I think for now I am just gonna create a small default project with most of the things in place in the `/apps `directory next to the other services. Once we fully converted - we can remove the exisiting ts projects and potentially the whole turbo repo stuff (feels bad man) - although turborepo might still be useful paired with tygo 🤔

libs:
- Api: [gin](https://github.com/gin-gonic/gin)
- Scraping: [colly](https://github.com/gocolly/colly)

tooling:
- Live reload: [air](https://github.com/cosmtrek/air)
- TS Generator: [tygo](https://github.com/gzuidhof/tygo)

<img src="https://github.com/ropfoo/tonemato/assets/18482002/39b90505-2a67-464e-baf7-bd2083af1ac3" width=300 />

// CC: @robinduerhager

**Comment by robinduerhager** [comment]
I like the puns in [gin](https://github.com/gin-gonic/gin). Approved 👍 .
